version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./models:/app/models
    environment:
      - DEBUG=true
      - DATABASE_URL=postgresql://postgres:password@db:5432/vizart_db
      - REDIS_URL=redis://redis:6379/0
      - ENABLE_GPU=false
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=vizart_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ../frontend:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev

volumes:
  postgres_data: